[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "POPLib"
authors = [{name = "Vishruth Rao and Team 1294's Programming subteam", email = "info@packofparts.org"}]
dynamic = ["version", "description"]
