name: Package Publishing

on:
  release:
    types: [created]

jobs:
  publish:
    name: Package Publishing
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checking out Code
      uses: actions/checkout@v4

    - name: Setting up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Publishing
      run: ./gradlew publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
